import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";

import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";

import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";

import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>portfolioofmine</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10  md:px-40 dark:bg-gray-900 ">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">Developed by Jordi</h1>
            <ul className="flex items-center">
              <div className="flex">
                <li className="mr-3">
                  <a class="" href="#intro" title="intro">
                    Intro
                  </a>
                </li>
                <li className="mr-3">
                  <a class="" href="#about" title="about">
                    About
                  </a>
                </li>
                <li className="mr-3">
                  <a class="" href="#services" title="services">
                    Services
                  </a>
                </li>
                <li className="mr-3">
                  <a class="" href="#works" title="works">
                    Works
                  </a>
                </li>
                <li className="mr-3">
                  <a class="" href="#contact" title="contact us">
                    Say Hello
                  </a>
                </li>
              </div>

              {/* <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li> */}
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Jordi Burger
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl">
              Designer, Developer & Analyst
            </h3>
            <p className="text-base py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto">
              Lets fight for a better future!
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={deved} fill style={{ objectFit: "cover" }} />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1">Services</h3>
            <p className="text-base py-5 leading-8 text-gray-800">
              <span className="text-teal-500">
                Using Design and Technology{" "}
              </span>
              to open up digital space and information systems for everyone.
              Design Cities, its infrastructure and make them secure. Technology
              should be a tool to design efficienct infrastructure enhance
              cultural and technical information systems for the better.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image class="mx-auto" src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">Web Development</h3>
              <p className="py-2">Frontend Development</p>
              <h4 className="py-4 text-teal-600">Tools:</h4>
              <p className="text-gray-800 py-1">HTML5, CSS ,JavaScript</p>
              <p className="text-gray-800 py-1">React.js</p>
              <p className="text-gray-800 py-1">Tailwindcss</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image
                class="mx-auto"
                src={consulting}
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Cyber Security: Red Team
              </h3>
              <p className="py-2">Penetration Testing</p>
              <h4 className="py-4 text-teal-600">Tools:</h4>
              <p className="text-gray-800 py-1">...</p>
              <p className="text-gray-800 py-1">...</p>
              <p className="text-gray-800 py-1">...</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image class="mx-auto" src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Cyber Security: Blue Team
              </h3>
              <p className="py-2">
                Minimalistic Desing and effective knowledge management systems
              </p>
              <h4 className="py-4 text-teal-600">Tools:</h4>
              <p className="text-gray-800 py-1">...</p>
              <p className="text-gray-800 py-1">...</p>
              <p className="text-gray-800 py-1">...</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1">Services</h3>
            <p className="text-base py-5 leading-8 text-gray-800">
              <span className="text-teal-500">Using Design and Technology</span>
              to open up digital space and information systems for everyone.
              Design Cities, its infratructure and make them save - thats the
              vision. Society becomes a Start up.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg-flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                className="rounded-lg objet-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web2}
                className="rounded-lg objet-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web3}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web4}
                className="rounded-lg objet-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web5}
                className="rounded-lg objet-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web6}
                className="rounded-lg objet-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
